apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtest-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webtest-service
            port:
              number: 3000
