apiVersion: v1
kind: Service
metadata:
  name: "webtest-service"
  labels:
    app: "webtest"
    tier: app
spec:
  selector:
    app: "webtest"
    tier: app
  ports:
    - name: web1
      port: 3000
      targetPort: 3000  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "webtest-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "webtest"
      tier: app
  template:
    metadata:
      name: "webtest"
      labels:
        app: "webtest"
        tier: app
    spec:
      containers:
        - name: "webtest"
          image: "sachinpoddar/webtest:latest"
          resources:
            requests:
              memory: "2G"
              cpu: "2000m"
          imagePullPolicy: "Never"
          ports:
            - name: web1
              containerPort: 3000
          env:
            - name: TARGET_ENV
              value: "local"
            - name: INGRESS_HOSTNAME
              value: "localhost"
   
              